types:
  test:
    cost: 100
    items:
      80:
        - 35,0
        - 36,0
        - 37,0
    reward:
      35,0:
        money: 500
        cmd: 
          - say Congratz on winning
        fireworks: 2